#!/bin/sh

function make_service () {
    SERVICE_DIR=$1;
    SERVICE_NAME=$2
    touch $SERVICE_DIR/$SERVICE_NAME.js;
    endpointGet='`${env.BASE_URL}/'"${SERVICE_NAME}"'?${params}`'
    endpoint='`${env.BASE_URL}/'"${SERVICE_NAME}"'`'
    echo "import { ApiUtils, constants } from '../utils/api'
import env from '../env'
const endpoint = ${endpoint}
const endpointParams = params => ${endpointGet}

const encodeData = data => Object.keys(data).map(key => [key, data[key]].map(encodeURIComponent).join('=')).join('&')

export class ${SERVICE_NAME}Service {
  ${SERVICE_NAME}Get ({ body = {} }) {
    let newEndpoint = endpointParams(
      encodeData({
        reference: env.partner
      })
    )
    return ApiUtils.get({endpoint: newEndpoint, headers: {ref: env.partner}})
  }
  ${SERVICE_NAME}Post ({ body = {} }) {
    return ApiUtils.post({endpoint, headers: {ref: env.partner, ct: constants.json}, body})
  }
}

export default new ${SERVICE_NAME}Service()
" > $SERVICE_DIR/$SERVICE_NAME.js;
}

function touch_module_index () {
    SERVICE_NAME=$1
    MODULE_DIR=$2
    SERVICE_NAME_CAP="$(tr '[:lower:]' '[:upper:]' <<< ${SERVICE_NAME:0:1})${SERVICE_NAME:1}"
    echo "export { default as ${SERVICE_NAME_CAP} } from './${SERVICE_NAME_CAP}'" >> $MODULE_DIR/index.js
}

SERVICE_NAME=$1
PROJECT_DIR=$2;
SERVICE_DIR=$PROJECT_DIR/src/services
MODULE_DIR=$PROJECT_DIR/src/store/modules

make_service $SERVICE_DIR $SERVICE_NAME
touch_module_index $SERVICE_NAME $MODULE_DIR
echo "[DONE]"
